### PR TITLE
fix: message toggle

### LINKED ISSUE #58: Message visibility toggle only turns messages off (doesn't actually toggle)
The Toggle/On/Off visibility of message `>` Toggle action seems to only turn message visibility **off** rather than actually toggle it.

(The On and Off actions seem to work as expected)

Demo:
https://github.com/bitfocus/companion-module-getontime-ontime/assets/44452336/f8f6b2c8-f875-4241-867b-25b8bb0f09f2

### LINKED ISSUE #60: Event indexing 0 or 1 ?
The object `selectedEventIndex` is ofcorece zero based internally
but all out receiving ws API's expect 1 based

Should we +1 to the companion variable `selectedEventIndex`  so that if the user send back this value it will have the same result?

### PR DESCRIPTION
**Pull request by alex-Arc**
fixes #58
fixes #60 

- fixes bad toggle logic for Message Visibility action
- change the `selectedEventIndex` variable to be 1 based index

### CODE REVIEW

File: src/v3/actions/message.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { MessageState } from '../ontime-types'
 export function createMessageActions(ontime: OntimeV3): { [id: string]: CompanionActionDefinition } {
 	function messageVisibility(action: CompanionActionEvent): void {
 		const destination = action.options.destination as keyof MessageState
-		const visible = action.options.value === 2 ? !ontime.state.message[destination] : action.options.value
+		const visible = action.options.value === 2 ? !ontime.state.message[destination].visible : action.options.value
```
Comment (cpvalente) [inline src/v3/actions/message.ts:11]: I am not too familiar with the code here, but I am not sure why we are negating the visible value from ontime?

**Review by cpvalente — APPROVED** [review]
Good work

File: src/v3/actions/message.ts (hunk 1 above)
Comment (alex-Arc) [reply src/v3/actions/message.ts:11]: we are toggling depending on the value in ontime
if visible -> send hide
if hidden -> send visible
