### PR TITLE
fix offset feedback calculation

### LINKED ISSUE #91: Rundown Offset Feedback not Working
If I add a Feedback for rundown Offset the Ahead, Behind, Ontime options are always false. Ahead or Behind is always true

Ontime Version: 3.9.4
Plugin Version: v4.3.0

# Negative Offset
Image
Image
Image
Image

# Positive Offset
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by 12xx12**
The original code had a mismatch on the switch/case statement in the offset callback. Now uses a enum to switch on

Fixes #91

### CODE REVIEW

**Comment by 12xx12** [comment]
@cpvalente

File: src/v3/feedbacks/offset.ts [hunk 1]
```diff
@@ -3,19 +3,28 @@ import { OntimeV3 } from '../ontimev3'
...
+	On = 'on',
+	Behind = 'behind',
+	Ahead = 'ahead',
+	Both = 'both',
+}
+
 export function createOffsetFeedbacks(ontime: OntimeV3): { [id: string]: CompanionFeedbackDefinition } {
 	function offset(feedback: CompanionFeedbackBooleanEvent): boolean {
-		const state = feedback.options.state
+		let state = feedback.options.state
```
Comment (alex-Arc) [inline src/v3/feedbacks/offset.ts:15]: a small suggestion
you can cast state immediately and then keep state as a constant 
```suggestion
		const state = feedback.options.state as as OffsetState
```

**Review by alex-Arc — APPROVED** [review]
Thank you, good catch
I've left one small suggestion

File: src/v3/feedbacks/offset.ts (hunk 1 above)
Comment (Marc-Lorenz) [reply src/v3/feedbacks/offset.ts]: good idea - done

Comment (12xx12) [reply src/v3/feedbacks/offset.ts]: Good idea - done

**Review by alex-Arc — APPROVED** [review]
